name: website1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/breakfast.jpg
    - assets/images/lunch.jpg
    - assets/images/dinner.jpg
    - assets/images/snack.jpg
    - assets/images/dessert.jpg
    - assets/images/side_dish.jpg
    - assets/icon/app_icon.png

flutter_icons:
  image_path: "assets/icon/app_icon.png"
